### ISSUE TITLE
New "Configuration/settings" screen

### ISSUE THREAD

**Issue by MattF-NSIDC** [faunalia/qgreenland-plugin#10]
Based on this mockup (see the "NOTE"s), we were envisioning the "mirror-selection" and "download location selection" settings could be combined in to one settings screen, and all settings there would be saved between QGIS sessions. The settings screen should only be automatically displayed once on first launch of the plugin, but accessible any time through a dedicated menu.

![image](https://user-images.githubusercontent.com/18539827/138312584-088775ac-5468-41e8-b0bf-663b9b57718f.png)

**Comment by ghtmtt** [comment]
@MattF-NSIDC I've some ideas, let me know what you think:

* instead of having a separated wizard for the server list tab that will be opened only at the first time, we can easily store all the setting(s) in the `QgsSetting` class, in the same way we are currently doing for the saving path
* having them stored in the settings, if the user change some values they will be automatically filled in the various boxes

This simplifies a little bit the plugin overflow and avoid to have different UI(s).

But anyway, let me know what you think and if this idea is suitable for you!

**Comment by ghtmtt** [comment]
ups, just saw what you wrote here: https://github.com/faunalia/qgreenland-plugin/issues/11#issuecomment-982167702

I'll go in that direction :)

**Comment by MattF-NSIDC** [comment]
Looking great in pull request #27! Is there a way to access this menu if you have already applied settings once, for example if you want to change to a different mirror?
